config/routes.rb
Agrid::Application.routes.draw do
  root "pages#index"
  resources :users, except: [:destroy, :edit, :update ] do
    resources :shows, only: [ :index ]
  end
  resources :shows
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :media, presence: true
  validates :user, presence: true
  validates_datetime :show_time, allow_blank: true

  scope :to_watch, lambda { where(["show_time >= ?", Time.now]).order("show_time ASC") }
  scope :before_now, lambda { where(["show_time < ? OR show_time IS NULL", Time.now]) }
  scope :today_shows, lambda { where(["show_time BETWEEN ? AND ?", DateTime.now.beginning_of_day, DateTime.now.end_of_day]) }

  enum media: { tv: "tv", series: "series", movie: "movie" }

  def media_text
    I18n.t("activerecord.attributes.show.medias.#{media}")
  end
  def self.media_attributes_for_select
    media.map do |media, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.medias.#{media}"), media]
    end
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :shows, dependent: :destroy

  scope :others, ->(id) { where.not(:id => id)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize

  private
  def authorize
    unless logged_in? 
      redirect_to login_path, error: I18n.t("messages.login_required")
    end
  end

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @today_shows = current_user.shows.today_shows
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    user = User.where(:email => params[:login][:email]).first

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: I18n.t("messages.successfully_login")
    else
      flash.now[:error] = I18n.t("messages.login_error")
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: I18n.t("messages.successfully_logout")
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @user = (params[:user_id] && User.find(params[:user_id])) || current_user
    @next_shows = @user.shows.to_watch
    @old_shows = @user.shows.before_now
    render layout: !request.xhr?
  end

  def new
    @show = Show.new
  end

  def create
    @show = current_user.shows.build(show_params)
    if @show.save
      redirect_to @show, notice: I18n.t("messages.show_created")
    else
      render :new
    end
  end

  def show
    find_show    
  end

  private
  def show_params
    params.require(:show).permit(:name, :media, :show_time)
  end

  def find_show
    @show = Show.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [ :new, :create ]
  
  def index
    @users = User.others(current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: I18n.t("messages.successfully_signed_up")
    else
      render :new
    end
  end

  def show
    find_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @@flash_messages = ActiveSupport::HashWithIndifferentAccess.new(
    success: "alert-success", error: "alert-danger",
    alert: "alert-block", notice: "alert-success"
  )
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
          class: 'error_message'
      )
    end
  end

  def cancel_link(path)
    link_to I18n.t("menu.cancel_button"), path, class: "btn btn-danger", data: { confirm: I18n.t("messages.cancel_operation")  }
  end  

  def error_explanation(model)
    if model.errors.any?
      content_tag :div, id: "error_explanation", class: "alert alert-danger" do
        I18n.t("messages.error_explanation")
      end
    end
  end

  def bootstrap_class_for(flash_type)
    @@flash_messages[flash_type] || flash_type.to_s
  end  

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">  
  <title>Agrid</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Agrid", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to t("menu.shows"), shows_path %>
          </li>
          <li>
            <%= link_to t("menu.other_users_shows"), users_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <%= link_to t("menu.logout"), logout_path, method: :delete %>
          <% else %>
            <li>
              <%= link_to t("menu.login"), login_path %>
            </li>               
            <li>
              <%= link_to t("menu.signup"), new_user_path %>
            </li>
          <% end %>     
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class='alert <%= bootstrap_class_for(key) %>'>
        <%= value %>
      </div>
    <% end %>    
    <%= yield %>
  </div>


<%= javascript_include_tag "application" %>
</body>
</html>

app/views/pages/index.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
        <h1><%= t("views.pages.index.title") %></h1>
        <p class="lead"><%= t("views.pages.index.today_shows_title") %></p>
    </div>
</div>
<div class="row">
  <ul>
    <% @today_shows.each do |show| %>
      <li>
        <%= show.link_to_show %>
      </li>
    <% end %>
  </ul>      
</div>

app/views/shows/_form.html.erb
<%= error_explanation(@show) %>
<%= form_for(@show, builder: BootstrapFormBuilder) do |f| %>
   <%= f.text_field :name %>
   <%= f.select :media, Show.media_attributes_for_select %>
   <%= f.text_field :show_time %>

   <%= f.submit_and_cancel(cancel_link(root_path), t("form.save_button")) %>
<% end %>

app/views/shows/index.html.erb
<%= link_to t("menu.show.new_show"), new_show_path if current_user.id == @user.id %>

<h2>Próximas atrações</h2>
<ul>
  <% @next_shows.each do |show| %>
    <li><%= show.link_to_show %></li>
  <% end %>  
</ul>

<h2>Atrações antigas</h2>
<ul>
  <% @old_shows.each do |show| %>
    <li><%= show.link_to_show %></li>
  <% end %>  
</ul>

app/views/shows/new.html.erb
<h1><%= t("views.shows.new.title") %></h1>

<%= render "form" %>

app/views/shows/show.html.erb
<h1><%= t("views.shows.show.show_title", name: @show.name) %></h1>
<%= t("views.shows.show.media_title", media: @show.media_text) %>
<div class="row">
  <% if @show.show_time.present? %>
    <%= t("views.shows.show.show_time_title", media: l(@show.show_time, format: :short)) %>  
  <% end %>
</div>

app/views/users/_form.html.erb
<%= error_explanation(@user) %>
<%= form_for(@user, builder: BootstrapFormBuilder) do |f| %>
   <%= f.text_field :name %>
   <%= f.text_field :email %>
   <%= f.password_field :password %>
   <%= f.password_field :password_confirmation %>
   <%= f.submit_and_cancel(cancel_link(root_path), t("views.users.form.signup_button")) %>
<% end %>

app/views/users/index.html.erb
<h1>Usuários</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
    </li>
  <% end %>  
</ul>

app/views/users/new.html.erb
<h1><%= t("views.users.new.signup_title") %></h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.name%></h1>

<div>
  <label><%= t("views.users.show.email") %></label>:<label><%=@user.email%></label>
</div>

<%= link_to t("views.users.show.user_shows_link"), user_shows_path(@user), "data-toggle" => "modal", "data-target" => "#user_shows_modal" %>
<!-- Modal -->
<div class="modal fade" id="user_shows_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>